language: cpp
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-4.9
    - gfortran-4.9
    - cmake

before_install:
  # Setting environement
  - export CMAKE_ARGS="-DCMAKE_BUILD_TYPE=debug -DBUILD_TESTS=ON"
  - |
    if test "$TRAVIS_OS_NAME" == "linux"; then
        export DO_COVERAGE=true
        export CMAKE_ARGS="$CMAKE_ARGS -DCODE_COVERAGE=ON"
        pip install --user codecov
    else
        export DO_COVERAGE=false
    fi
  # Install Linux stuff
  - |
    if test "${TRAVIS_OS_NAME}" == "linux"; then
        export CC=gcc-4.9
        export CXX=g++-4.9
        export FC=gfortran-4.9
    fi
  # Install OS X stuff
  - |
    if test "$TRAVIS_OS_NAME" == "osx"; then
        brew update
        brew rm gcc
        brew install gcc
        export CC=clang
        export CXX=clang++
        export FC=gfortran
    fi

install:
  - cd ${TRAVIS_BUILD_DIR}/chemfiles && git submodule update --init
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build
  - cd build
  - cmake $CMAKE_ARGS ..

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make
  - ctest --output-on-failure

after_success:
  - |
    if ${DO_COVERAGE}; then
        codecov --gcov-exec=gcov-4.9
    fi
