name: Test

on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: configure cmake
        run: |
          export FC=gfortran-10
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=debug -DCHFL_FORTRAN_BUILD_TESTS=ON ..
      - name: enable coverage
        if: matrix.os == 'ubuntu-20.04'
        run: |
          python -m pip install --upgrade pip
          pip install codecov
          cd build && cmake -DCHFL_CODE_COVERAGE=ON .
      - name: build code
        run: cd build && make -j2
      - name: run tests
        run: cd build && ctest --output-on-failure
      - name: run extra checks
        run: |
          ./scripts/check-tests.py
          ./scripts/check-docs.py

      - name: collect coverage
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt install lcov
          lcov --capture --directory . --output-file coverage.info
      - uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-20.04'
        with:
          fail_ci_if_error: true
          verbose: true
